### ISSUE TITLE
On roster student show page, add list of repos for which student is an owner, or a collaborator

### ISSUE THREAD

**Issue by ryangormley81** [project-anacapa/anacapa-github-linker#89] opened 2019-10-14 21:28 UTC
- [ ] Create a new route in the controller at, for example `https://ucsb-cs-github-linker.herokuapp.com/courses/31/roster_students/2514/repos`
- [ ] At that new route, have a placeholder page that repeats some of the information from the `roster_student` show page: First Name, Last Name, github id, email, as a table with one row of headers, and one row of data.   Email should be a link to the email, github should be a link to github.com/username
- [ ] Use the github api to fetch a list of repos that the student is an owner of that are from the organization.   Make the list an HTML table with column headings repo name, public/private.  The reponame should be a link to the repo.
- [ ] Use the github api to fetch additionally, any repos on which the student is a collaborator.  Add a column heading for owner/collaborator.  Indicate in that column whether the student is an owner or a collaborator on the repo.

**Comment by pconrad** [comment] 2019-10-14 22:53
A few notes:

If you look at https://github.com/project-anacapa/anacapa-github-linker/blob/dcbf82b4503e3fdc862ca3b0164735326fe3becb/app/controllers/courses_controller.rb#L185 you'll see this code:

```ruby
    def machine_user
      client = Octokit_Wrapper::Octokit_Wrapper.machine_user
    end
```

That private method (which we should probably factor out into some kind of helper mix-in) gives you a handle to the `machine_user`, which is a Github User that has access to the organization, and that can do Github operations on behalf of the application.

Next, look at line 139 in the same file.  We see that `machine_user` can be used to do Github API calls through Octokit.  The documentation for Octokit is here: <https://github.com/octokit/octokit.rb> and here <http://octokit.github.io/octokit.rb/>

Note that the key to unlocking the mystery is that`machine_user` is an instance of `Client` in the Octokit api, so the methods of `Client` are the ones you can invoke on `machine_user`.  

Those are here: <https://www.rubydoc.info/github/pengwynn/octokit/Octokit/Client>

```ruby
result = machine_user.create_org_hook(
        @course.course_organization,
        {
          :url => webhook_url,
          :content_type => 'json',
          :secret => ENV['GITHUB_WEBHOOK_SECRET']
        },
        {
          :events => ['*'],
          :active => true
        }
      )
```

In your case, you want to look up repos in an organization that belong to a particular user.  You'll probably be looking for method such as these:

**Comment by ProbablyFaiz** [comment] 2019-10-31 08:23
Did a lot of research into the GitHub repos display for student page and it's actually quite a bit more challenging than it would appear on its surface. The problem is that GitHub's API is structured in a way that requires a huge amount of data to be requested to get at this pretty narrow scope. Here are the options I've explored and why they either don't work or are resource prohibitive:

* Asking the GitHub API for a list of a user's repos only returns their personal repos, not any repos they've created or contributed to in any organizations.

* Another option is to fetch all of the repos in the organization, but the output lists the organization and not the user as the owner, so you would have to make a separate request for every single org repo to find out which users contribute to the repository and then list only those repos which the user contributes to. As you might imagine, this can be hundreds of API calls for a single user's repo list which makes it tremendously inefficient.

* GitHub has an Events API which allows you to get certain activity data within the past 90 days about some user or organization. There is [an API endpoint](https://developer.github.com/v3/activity/events/#list-events-for-an-organization) which allows you to get all the events in an organization that would be visible to a specific user. You could search through this list of events for a set of repositories that the user has triggered commit/push/other write events for without making tons of requests. Unfortunately, you can only make this request if your authentication token is specifically for the user in question, meaning that a different user cannot get this narrow information set even if they own the organization.

* You could use the GitHub Events API to fetch all events in the organization in the past 90 days and then sift through these for write events by the user to figure out which repos they were members of. This would request EVERY organization event so it would require requesting a huge amount of information just to get the user's organization repos. And of course, if there is any repo that was last modified more than 90 days ago it won't show up (not an issue for the quarter system but could cause occasional issues for other schools). 

Given these poor options, I don't believe it's doable to create these lists when a TA/instructor/admin goes to view the user's repos. It may be most feasible to simply maintain these lists for each users in the course of real-time webhook integration so that when a user triggers a commit/push/other write event, the program adds the repo the event was made in to the user's repo list unless the repo is already in the list. It's of course not ideal and requires a much more thoughtful implementation but it does not seem to me at the moment that there is an easy way to do this unless I'm missing something.

**Comment by ProbablyFaiz** [comment] 2020-01-03 04:37
Closing this issue as this functionality has now been implemented.

**Closed by ProbablyFaiz** 2020-01-03 04:37 UTC
